apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: voting
  POSTGRES_PASSWORD: supersecret
  POSTGRES_CONNECTION_STRING: Host=postgres;Port=5432;Database=votingdb;Username=voting;Password=supersecret;Pooling=true;Include Error Detail=true;