apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp-deployment
  labels:
    app: votingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votingapp
  template:
    metadata:
      labels:
        app: votingapp
    spec:
      containers:
        - name: votingapp
          image: votingapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: Redis__ConnectionString
              value: "redis:6379"
            - name: Redis__Key
              value: "votes"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
