apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingresults-deployment
  labels:
    app: votingresults
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votingresults
  template:
    metadata:
      labels:
        app: votingresults
    spec:
      containers:
        - name: votingresults
          image: votingresults:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: POSTGRES_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_CONNECTION_STRING
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20