apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
  labels:
    app: votingapp
spec:
  type: NodePort
  selector:
    app: votingapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080