apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: Redis__ConnectionString
              value: "redis:6379,abortConnect=false"
            - name: Redis__Key
              value: "votes"
            - name: Redis__PollingIntervalSeconds
              value: "2"
            - name: POSTGRES_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_CONNECTION_STRING
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20